apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-deployment
  namespace: default
  labels:
    k8s-app: new
spec:
  selector:
    matchLabels:
      k8s-app: new
  replicas: 3
  template:
    metadata:
      labels:
        k8s-app: new
    spec:
      containers:
        - name: nginx
          image: docker.pkg.github.com/tnmnet/new-app/new-app-02-23:v1
          ports:
            - name: http
              containerPort: 80
              
...
apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
  namespace: awesomeapps
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJkb2NrZXIucGtnLmdpdGh1Yi5jb20iOiB7CgkJCSJhdXRoIjogImRHNXRibVYwT2pGaE1EWmhPR1ZpWm1FMVlUYzBabVZrTXpsak1qRmhOV1V5WWpSbVpHRmxOV0l3TlRJMFpqUT0iCgkJfSwKCQkiZ2hjci5pbyI6IHsKCQkJImF1dGgiOiAiZEc1dGJtVjBPalJoWTJVd05qa3pPV0ZpTmpNNFpUbG1NV0UzT1RobE1XRm1OVFU0TnprNFlXVmhORE0xTkRFPSIKCQl9LAoJCSJyZWdpc3RyeS5naXRsYWIuY29tIjogewoJCQkiYXV0aCI6ICJkSEpwZG1Wa2FUTXpPbEYxYVV0RGMyaGlVMVl6YzBWM1pVVkRTSGxIIgoJCX0KCX0sCgkiSHR0cEhlYWRlcnMiOiB7CgkJIlVzZXItQWdlbnQiOiAiRG9ja2VyLUNsaWVudC8xOS4wMy4xMyAobGludXgpIgoJfQp9
type: kubernetes.io/dockerconfigjson
